### ISSUE TITLE
v2.0.2 release checklist

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi#2579]
## Make a perfect tarball

- [x] Update the major,minor,release,greek version numbers in `VERSION`
- [x] Update the shared library version number(s) in `VERSION` [per the GNU Libtool shared library version number rules](https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html) (pro tip: you probably want to use `git log --stat --no-merges last_release_tag..HEAD`)
- Update all documentation files (especially including dates and version numbers), including:
  - [x] `README`: all relevant updates, build options, etc.  Be sure to update the date near the top of the file.
  - [x] `AUTHORS`: via `contrib/dist/make-authors.pl` (and commit the result)
  - [x] `NEWS`: List all user-noticable changes
  - [x] `LICENSE`: Update the years in the copyright notices
  - [x] ...any other doc files that may not be included in this list
- [x] Make final `openmpi-x.y.z.tar.gz` and `openmpi-x.y.z.bz2` tarballs using the _make_dist_tarball_ script in contrib/dist

## Ensure that the tarball actually works
- [x] Ensure openmpi `make distcheck` passes
- Build and install Open MPI (from a tarball)
  - [x] Check that the version number and release date is correct in the installed man pages
- [x] Build and run the examples in the tarball
  - [x] MPI / C bindings
  - [x] MPI / C++ bindings
  - [x] MPI / All three Fortran bindings
  - [x] OSHMEM / C bindings (don't run if not using ikrit)
  - [x] OSHMEM / Fortran bindings (don't run if not using ikrit)
- [x] Build and install the IBM tests from the `ompi-tests` repo
  - [x] Ensure the tests pass with at least 1 or 2 different MPI transports
- With a prior release tarball from the same release series:
  - [x] Build and install Open MPI
  - [x] Build all the examples in the tarball (against the prior OMPI release)
  - [x] Build the IBM tests from the `ompi-tests` repo (against the prior OMPI release)
  - [x] `rm -rf` the installation of the prior release
  - [x] Set `LD_LIBRARY_PATH` to point to the installation of the new Open MPI
  - [x] Run examples, make sure they still work
  - [x] Run IBM tests, make sure they still work

## Test packaging
- [x] Ensure that building an Open MPI source RPM works on a RHEL system
- [x] Ensure that building the Open MPI binary RPM works on a RHEL system (note had to do hacking on buildrpm.sh script and it doesn't report correct information about where rpms are installed, at least not on my RHEL7.2 system running as root)
- [x] Install both RPMs on an RHEL system
- [x] Test building and running the IBM tests against the RPM-installed Open MPI
- [x] Test building a MPI-based program with the output from `pkg-config` with the RPM-installed `openmpi.pc`
- [x] Test that uninstall of the rpm works

## Do the release
- [x] `git tag -a vX.Y.Z` on the appropriate Open MPI release branch
- [x] `git push --tags --dry-run` to the ompi repo.  Remove `--dry-run` when you're convinced it is correct.
- Publish the tarballs on the Open MPI web site
  - If Z is 0 (i.e., this is the first release in a series):
    - [x] `cp -r software/ompi/v2.0 software/ompi/vRELEASE` (where RELEASE is X.Y)
    - [x] Edit each file in the new directory to update for the new release
    - [x] Remove all prior tarballs from the `downloads` subdirectory
  - [x] Add the tarball + SRPM files to the appropriate `ompi-www` directory (e.g., `software/ompi/v2.0/downloads/`).
  - [x] Update the `md5sums.txt` and `sha1sums.txt` file in that directory (e.g., `md5sum openmpi* > md5sums.txt`)
  - [x] Update the `latest_snapshot.txt` file in that directory
  - [x] Update `version.inc` in one directory up
  - [x] Update `index.php` (in the same directory as `version.inc`) and add the prior release to the `$versions[]` array so that it shows up in the older releases list
  - [x] Update the top-level `index.php` with a news bullet about this release.  It is likely possible to guess the correct URL that will be used to web archive the announcement mail sent to announce@lists.open-mpi.org
  - [x] Git commit and push all these changes
- Publish the newest version of the man pages
  - [x] Download and un-tar a new Open MPI release tarball (no need to config/rebuild/install it)
  - [x] Get a git clone of the Open MPI repo, checkout the branch that you are releasing
  - [x] Check out the vA.B.C release tag that you are releasing
  - [x] In the top-level directory of the expanded tarball, run
  `contrib/dist/make-html-man-pages.pl` from the git clone checked out at the vA.B.C release tag (this file is *not* in the release tarball)
    - This will take a little time because it will configure and build Open MPI, and then convert all the man pages to HTML.
    - You can ignore warnings about the "" macro not being recognized
  - In the `ompi-www` repo:
    - [x] `git rm -rf doc/vRELEASE` and commit
    - [x] `mkdir doc/vRELEASE`
    - [x] `cp -rp YOUR_BUILD_TREE/man-page-generator/php/* .`
    - [x] `git add doc/vRELEASE`
    - [x] If this is a new release series update `doc/index.php` to list the new directory and git add it
    - [ ] `git commit -s`
  - [x] Git push all web site changes
  - [x] Verify the live web site to ensure all changes are both present and correct
- [x] Close the relevant Github milestone in `open-mpi/ompi`
- [x] Re-target all still-open v2.0.2 issues for v2.0.3 or v2.1.0, as appropriate
- [x] Ensure that new Github milestones exist in `open-mpi/ompi` for the next release
- [x] Update the Open MPI version number in `VERSION` to `<NEXT_VERSION>` and get `greek` to `a1`
- [x] Send an email to the `announce@lists.open-mpi.org` mailing list announcing the release
- [x] Verify that the URL used to link to the release announcement (to `announce@open-mpi.org`) is correct on the front Open MPI web page.

**Comment by boegel** [comment]
Is there an ETA for the final 2.0.2 release?

**Comment by hppritcha** [comment]
@boegel we got feedback on rc2 and a few other things we are investigating.  We may need to role an rc3.  I'd say earliest for 2.0.2 release would be late next week, although its looking more like third week of January.  Of course there can always be surprises.

**Comment by boegel** [comment]
@hppritcha OK, thanks for the info, much appreciated. Good luck with getting things stable, looking forward to the new release!

**Comment by boegel** [comment]
Any updates on the ETA for the final 2.0.2 release?

I don't want to be pushy at all, please take the time you need, it's just that we'll need to decide to go forward with OpenMPI 2.0.1 or wait for 2.0.2 soonish...

**Comment by jsquyres** [comment]
@boegel We're going to make another -- hopefully final -- v2.0.2 rc tomorrow!

**Comment by boegel** [comment]
@jsquyres Thanks for the update! Any idea how much time there would be between the this rc and the final v2.0.2 release?

**Comment by jsquyres** [comment]
Hopefully very little.  😄 

v2.0.2rc4 just released: https://www.mail-archive.com/devel@lists.open-mpi.org/msg19897.html

**Comment by boegel** [comment]
@jsquyres Do you have a more exact ETA yet for the final v2.0.2 release?

I need to make a decision really soon now whether or not to go forward with v2.0.2 or stick to v2.0.1 (which I'd rather not, obviously).

**Comment by jsquyres** [comment]
It has now been released!

https://www.open-mpi.org/software/ompi/v2.0/

The announcement should show up here shortly: https://www.mail-archive.com/announce@lists.open-mpi.org/

**Comment by boegel** [comment]
Fantastic, thanks @jsquyres and everyone else in the OpenMPI team for the hard work!
