### ISSUE TITLE
v3.0.0 branch checklist

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/ompi#3015]
The Open MPI pre-release mechanism requires more steps than simply branching master in a workarea and pushing back to open-mpi/ompi on github.  In particular, steps need to be taken to make sure nightly tarballs of the branch are being built and that there is a place for these tarballs on the Open MPI webpages.  See [v2.x](https://www.open-mpi.org/nightly/v2.x) for an example of what is needed on the Open MPI Download webpages.

# In the `ompi` repo

- On the `master` branch:
  - [x] Run `contrib/dist/make-authors.pl` to update the `AUTHORS` file
  - [x] Commit/push the resulting `AUTHORS` back to GitHub (on `master`)
- Create the new release branch:
  - [x] `git checkout -b vA.x`, where `A` is a new integer greater than any other value that has been used before.
  - [x] Make sure `VERSION` reflects the correct `vx.y.0` value, and that `greek` is set to `a1`
  - [x] Push back the new branch back to the OMPI GitHub repository
- Back on the `master` branch:
  - [x] Update `contrib/build-server/openmpi-nightly-tarball.sh` to include the new branch in the list of branches for which to make nightly tarballs.
  - [x] Update `VERSION` to increment major/minor to be beyond the version on the new branch.
  - [x] Push back changes to master branch on the OMPI GitHub repository 
- On Github (these steps require admin authority on the OMPI GitHub repo):
  - [x] Protect the new branch
  - [x] Select the following options:
    - [x] Require pull request reviews before merging
      - [x] Include administrators
    - [x] Restrict who can push to this branch
      - [x] Select an appropriate `ompi` org team, such as `open-mpi/ompi-gatekeeper`

# In the `ompi-www` repo:

- [x] in `ompi-www/nightly` create a new directory with the name of the new branch
- [x] Copy the `index.php` from one of the existing version subdirectories in `ompi-www/nightly` in to the new directory and edit to update the text to the newly created branch version.
- [x] Edit the  `Upcoming  release series`  section of `ompi-www/nightly/index.php` as appropriate for the new branch.
- [x] Push changes back to GitHub
- [x] Verify that the changes go live on www.open-mpi.org within 15 minutes

**Comment by hppritcha** [comment]
this is done, closing
