### ISSUE TITLE
Track RTE-related commits that need to go to v3.0

### ISSUE THREAD

**Issue by rhc54** [open-mpi/ompi#3289]
- [ ] commits from #3441 (ABI change !)
- [x] commits from #3356 (PR #3365)
bb1aaa32860eab1e0d1963fa6dbf0c38ef5f91ec
- [ ] commits from PR #3429 
3a13bd6ab4fa5be6e6ac732d4e97f8ec576d31ea
- [ ] commits from #3350 
67156556ce889f50230439b82d38b4944adb3520
- [ ] commits from #3344 
1585854335268e7b558b05c41219a9c35e12984e
- [ ] commits from #3331 
4af7a0827fa0bfc2d7d22016edd2ed3347fdd5ab
- [ ] commits from #3336 
0500cc1c66469155c8c92473c7f2209afc728b82
- [ ] commits from #3335 
9f73974fe1cfd616c5f8a9e5a23f33eb14c08414
- [ ] commits from #3310 
27fa8aabd67f2e4fad7f63a5d0fb2e4398663c4f
af3a6e1a295d06fecaa0ab0883c16e3a7df0ceb6
- [ ] commits from #3325
97e38e6d847ac3b64fe650bafe81b4c1e633a56c
- [ ] commits from PR #3222 
bb81f3b5db48d5916e8b438d84d15495ca8215d3
- [ ] commits from PR #3301 
b526bca56c3ca6e01db8d9196c248ac153bca526
b33b4607df12897d1678efacb0bf03d7d24db75c
e101f2b3f995426b147a826fc82a84e07e913adf
- [ ] commits from PR #3294 
a29ca2bb0d7e0a1f4749fe88c1aa6bd09837d0a0
- [ ] commits from PR
36d660e07a597da01c4d16c14bb8ba81a0973f80
- [ ] commits from PR #3287
db8943cedda1d4b1887085cb80133c6057c545a0
- [ ] commits from PR #3284
b7e9711f4520b202a5c7d5b6b72f263aa4179e27
- [ ] Commits from PR #3282
40ca43e157c9e1bc441187cfbcf0fc1711365488
- [ ] Commits from PR #3281
734b90aa6b1c1b873cc85e11b74db6fe58df97ec
- [ ] Commits from PR #3280 
74863a0ea4c2cd29b504fe396cb442c297a7e704
- [ ] Commits from PR #3278 
393c4536eb165459d2dbcac0080aa348fff2d668
- [ ] Commits from PR #3259
92c996487c589ef8558a087ce2a9923dacdf0b99
- [ ] Commits from PR #3273
2cc5fea8beb270d3b722f57f4b59e0a0ccf0c14d
- [ ] Commits from PR #3249
7dd34d0c9a58c50f47295d866e675dcda91a5e07
- [ ] Commits from PR #3227 
55e4fba5f5633d08b283c247301c17926c4f5b6b
- [ ] Commits from PR #3218 
d645557fa01fd46bf80a61470759e74ecaede640
- [x] Commits from PR #3217 
74fd2c30af6fd71a82d3b5ddac3329f497b7be9e
75684dc2
 - [x] Commits from PR #3219
f8e1e3bed3866e9e71d0d782c396bacbe681c4bb
