### ISSUE TITLE
v3.0.2 Release Checklist

### ISSUE THREAD

**Issue by bwbarrett** [open-mpi/ompi#4993]
## Build the Release
- [x] Verify the major,minor,release,greek version numbers in `VERSION`
- [x] Update the `c:r:a` shared library version number(s) in `VERSION` [per the GNU Libtool shared library version number rules](https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html)
   - **NOTE:** It may be helpful to use a command like `git checkout BRANCH; git pull --rebase; git log --stat --topo-order --decorate TAG_FROM_PREVIOUS_RELEASE..HEAD` to examine the Git logs and see what has changed.
   - [x] *IF RELEVANT:* If this is a new backwards-compatible release on a single branch (i.e., this is `vx.y.z` where `z>1`), you probably want to examine `git log --stat --no-merges last_release_tag..this_branch_name` to see what source code files have changed (which directly impacts how to increment the `c:r:a` values).
  - [x] *IF RELEVANT:* If this is a new release series (e.g., `vx.y.0`), set `r` to 0 and increase `c` values by 10 compared to the first release in the prior series (i.e., `vx.(y-1).0` or `v(x-1).0.0`, as relevant).
  - [x] *IF RELEVANT:* If this is a new backwards-compatible release series (i.e., `vx.y.0`, where `y>1`), set`a` values to 10 so that the shared libraries will be ABI compatible with the prior release series.
  - [x] *IF RELEVANT:* If this is a new backwards-**IN**compatible release series (i.e., `vx.0.0`), set `a` values to 0 so that there is no possibility of users accidentally mixing shared library versions.
- [x] Update all documentation files (especially including dates and version numbers), including:
  - [x] `README`: all relevant updates, build options, etc.  Be sure to update the date near the top of the file.
  - [x] `NEWS`: List all user-noticeable changes.  Similar to setting shared library versions (above): 
       - Pro tip: if this is a new release on a single branch (i.e., this is `vx.y.z` where `z>1`), you probably want to examine `git log --stat --no-merges last_release_tag..this_branch_name` to see what has changed.
       - Pro tip: if this is a new release series (i.e., this is `vx.y.0` where `y>1`, or this is `vx.0.0`), you will need to be more creative in examining the git logs because this release is on a different branch than the prior release (`vx.(y-1).z`).  Hence, `git log ... last_release_tag..this_branch_name` will not necessarily give you need.  You may need to merge what has changed on your branch with what has changed on the prior release branch, depending on when the prior release branched from this branch.  Read the **SPECIFYING RANGES** section `gitrevisions(7)` for more details.
  - [x] `LICENSE`: Update the years in the copyright notices 
- [x] Create a tag for the release, matching the version being released (ie, `git tag -a v3.0.1 <HASH>`).  Verify <HASH> was a nightly tarball hash and that the [MTT](https://mtt.open-mpi.org/) results look good.  Push the tag for a release.
- [x] Run the [Tarball Builder Job](https://jenkins.open-mpi.org/jenkins/job/open-mpi.dist.create-tarball/) on Jenkins to build the tag as a release build.

## Publish the release
- [x] Update the web site to show the release
  - If Z is 0 (i.e., this is the first release in a series):
    - [ ] `cp -r software/ompi/vCURRENT_RELEASE software/ompi/vRELEASE` (where RELEASE is for the new release X.Y and CURRENT_RELEASE is the X.Y of the current release)
    - [ ] Edit each file in the new directory to update for the new release
        - [ ] Edit `timeline-graph.php` to indicate relevant dates, such as branching
    - [ ] Update `version.inc` to remove the "existing" versions from the previous release
    - [ ] Edit `software/ompi/nav.inc` and make this release series be the current stable release; shift other release series down as appropriate
    - [ ] Edit `nightly/index.php` to make this release series be the current stable release; shift other release series snapshot tarballs down as appropriate
    - [ ] Edit `software/ompi/current/version.inc` to set the new release series as the current software release.
  - [x] Add the new version in `version.inc`
  - [x] Update `timeline-graph.php` (in the same directory as `version.inc`) to add a date stamp to the timeline graph for the release of this version (i.e., call `milestone()` like it is for the other releases)
  - [x] Update the top-level `index.php` with a news bullet about this release.  It is likely possible to guess the correct URL that will be used to web archive the announcement mail sent to announce@lists.open-mpi.org
- [x] Publish the newest version of the man pages
  - [x] Download the man pages tarball from the Jenkins build (there will be a link in the description of the build on Jenkins, note that the URL is only good for 30 days from the build)
  - [x] Untar the tarball in the top level of the ompi-www directory
  - [x] `git add doc/vRELEASE`
  - [ ] If this is a new release series:
      - [ ] Update `doc/index.php` to list the new directory and git add it
      - [ ] Remove and re-create the `current` sym link to point to the correct directory and git add it
- [x] `git commit -s` to commit all the web site changes
- [x] `git push` all web site changes
  - [x] Verify the live web site to ensure all changes are both present and correct (updates happen every 15 minutes or so...)
- [x] Close the relevant Github milestone in `open-mpi/ompi`
- [x] Send an email to the `announce@lists.open-mpi.org` mailing list announcing the release
- [x] Verify that the URL used to link to the release announcement (to `announce@open-mpi.org`) is correct on the front Open MPI web page.

## Prep for next release in series
- [x] Re-target (change milestone) all still-open issues for the new release to the next major or minor release of Open MPI as appropriate
- [x] Ensure that new Github milestones exist in [GitHub](https://github.com/open-mpi/ompi/issues) for the next release
- [x] Update the Open MPI version number in `VERSION` to `<NEXT_VERSION>` and set `greek` to `a1`
- [x] Open a duplicate of this issue for the next release in this series.
